workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic_api_key
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.ezvstudio.snake
      vars:
        BUNDLE_ID: "com.ezvstudio.snake"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          cd ios && pod install
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - renanrpm@gmail.com
        notify:
          success: true
          failure: true
      # Descomente para enviar automaticamente para o TestFlight
      # app_store_connect:
      #   auth: integration
      #   submit_to_testflight: true
