workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: "Codemagic API"
    environment:
      ios_signing:
        provisioning_profiles:
          - com.ezvstudio.snake
      vars:
        BUNDLE_ID: "com.ezvstudio.snake"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Disable Swift Package Manager
        script: |
          flutter config --no-enable-swift-package-manager
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Generate Xcode project config
        script: |
          flutter build ios --release --no-codesign --config-only
      - name: Install pods
        script: |
          cd ios && pod install
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Flutter build ipa
        script: |
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID" || echo 0)
          BUILD_NUMBER=$((LATEST_BUILD_NUMBER + 1))
          flutter build ipa --release \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - renanrpm@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
